# Generated by Django 4.0.3 on 2022-03-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=4096, verbose_name='Вопрос')),
                ('question_type', models.CharField(choices=[('radio', 'Один ответ'), ('checkbox', 'Несколько ответов'), ('text', 'Текстовый ответ')], default='radio', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048, verbose_name='Название теста')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество вопросов')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_variable', models.TextField(max_length=2048, verbose_name='Вариант ответа')),
                ('right_choice', models.BooleanField(default=False, verbose_name='Верный вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.test'),
        ),
        migrations.CreateModel(
            name='PassedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.BooleanField(verbose_name='Ответ верный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.question')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.questionchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
